name: uber_eats_restaurant_dashboard
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.3+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_messaging: ^12.0.3
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  cloud_firestore: ^3.4.5
  image_picker: ^0.8.5+3
  image_gallery_saver: '^1.7.1'
  firebase_storage: ^10.3.6
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  intl: ^0.17.0

  cached_network_image: ^3.2.1
  flutter_facebook_auth:

  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.4.0
  easy_localization: ^3.0.1
  font_awesome_flutter: ^10.1.0
  photo_view: ^0.14.0
  flutter_sound: ^8.3.9
  video_thumbnail: ^0.5.2
  video_compress: ^3.1.1
  flutter_native_image: ^0.0.6+1
  the_apple_sign_in: ^1.1.1
  numberpicker: ^2.1.1
  multiselect: ^0.0.7
  flutter_datetime_picker: ^1.5.1
  multi_select_flutter: ^4.1.2
  geolocator: ^7.7.1
  map_picker: ^0.0.3
  location: ^4.4.0
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.6
  google_maps_place_picker: ^2.1.0-nullsafety.3
  dotted_border: ^2.0.0+2
  datetime_picker_formfield: ^2.0.0
  random_string: ^2.3.1
  flutter_facebook_keyhash: ^0.0.4
  geoflutterfire: ^3.0.3
  video_player: ^2.4.2
  path_provider: ^2.0.10
  sticky_headers: ^0.3.0+2
  barcode_image: ^2.0.2
  image: ^3.2.0
  soundpool: ^2.3.0
  audioplayers: ^1.0.1
  # geocoder:
  #   git:
  #     https://github.com/aloisdeniel/flutter_geocoder.git

  # google_map_location_picker:
  #   git:
  #     url: git://github.com/lyokone/google_map_location_picker.git
  # permission_handler:
  # google_maps_flutter:
  # geocoder: any
  # geocoder:
  #   git:
  #     https://github.com/aloisdeniel/flutter_geocoder.git

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf